apiVersion: apps/v1
kind: Deployment
metadata:
  name: cfscraper-api
  labels:
    app: cfscraper-api
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cfscraper-api
  template:
    metadata:
      labels:
        app: cfscraper-api
        version: v1
    spec:
      containers:
      - name: cfscraper-api
        image: cfscraper:latest
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: cfscraper-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: cfscraper-secrets
              key: redis-url
        - name: LOG_LEVEL
          value: "INFO"
        - name: MAX_CONCURRENT_JOBS
          value: "10"
        - name: JOB_TIMEOUT
          value: "300"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
      imagePullSecrets:
      - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: cfscraper-api-service
  labels:
    app: cfscraper-api
spec:
  selector:
    app: cfscraper-api
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP

---
apiVersion: v1
kind: Secret
metadata:
  name: cfscraper-secrets
type: Opaque
stringData:
  database-url: "postgresql://user:password@postgres:5432/cfscraper"
  redis-url: "redis://redis:6379"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cfscraper-config
data:
  app.conf: |
    # CFScraper Configuration
    DEBUG=false
    LOG_LEVEL=INFO
    
    # Database Configuration
    DB_POOL_SIZE=20
    DB_MAX_OVERFLOW=30
    DB_POOL_TIMEOUT=30
    DB_POOL_RECYCLE=3600
    
    # Redis Configuration
    REDIS_MAX_CONNECTIONS=50
    REDIS_HEALTH_CHECK_INTERVAL=30
    
    # Cache Configuration
    CACHE_DEFAULT_TTL=3600
    CACHE_MAX_MEMORY_SIZE=104857600  # 100MB
    
    # HTTP Client Configuration
    HTTP_TIMEOUT=30.0
    HTTP_MAX_CONNECTIONS=100
    HTTP_MAX_RETRIES=3
    
    # Performance Configuration
    MAX_CONCURRENT_JOBS=10
    JOB_TIMEOUT=300
