"""Initial migration

Revision ID: 81481d6f6f74
Revises: 
Create Date: 2025-07-10 02:22:15.494430

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '81481d6f6f74'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_results',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('job_id', sa.INTEGER(), nullable=True),
                    sa.Column('task_id', sa.VARCHAR(), nullable=True),
                    sa.Column('status_code', sa.INTEGER(), nullable=True),
                    sa.Column('response_headers', sa.JSON(), nullable=True),
                    sa.Column('response_content', sa.TEXT(), nullable=True),
                    sa.Column('response_time', sa.INTEGER(), nullable=True),
                    sa.Column('content_length', sa.INTEGER(), nullable=True),
                    sa.Column('content_type', sa.VARCHAR(), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_job_results_task_id'), 'job_results', ['task_id'], unique=False)
    op.create_index(op.f('ix_job_results_job_id'), 'job_results', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_results_id'), 'job_results', ['id'], unique=False)
    op.create_table('jobs',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('task_id', sa.VARCHAR(), nullable=True),
                    sa.Column('status', sa.VARCHAR(), nullable=True),
                    sa.Column('scraper_type', sa.VARCHAR(), nullable=True),
                    sa.Column('url', sa.VARCHAR(), nullable=False),
                    sa.Column('method', sa.VARCHAR(), nullable=True),
                    sa.Column('headers', sa.JSON(), nullable=True),
                    sa.Column('data', sa.JSON(), nullable=True),
                    sa.Column('params', sa.JSON(), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
                    sa.Column('started_at', sa.TIMESTAMP(), nullable=True),
                    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
                    sa.Column('result', sa.JSON(), nullable=True),
                    sa.Column('error_message', sa.TEXT(), nullable=True),
                    sa.Column('retry_count', sa.INTEGER(), nullable=True),
                    sa.Column('max_retries', sa.INTEGER(), nullable=True),
                    sa.Column('progress', sa.INTEGER(), nullable=True),
                    sa.Column('progress_message', sa.VARCHAR(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_jobs_task_id'), 'jobs', ['task_id'], unique=1)
    op.create_index(op.f('ix_jobs_id'), 'jobs', ['id'], unique=False)
    # ### end Alembic commands ###
